#!/bin/sh
# This script sets some popular user configuration settings in an Ubuntu 10.04
# LTS GNOME system. Run this, then upgrade to 12.04 LTS (or later), and run
# test_lts_upgrade_user.py to confirm that settings were migrated properly. In
# particular this checks for gconf -> gsettings migration (and sometimes
# changing the format of the values) for popular settings, as well as custom
# panel/desktop launchers.
#
# You need to run this script in a fully running GNOME desktop session.

#
# (C) 2012 Canonical Ltd.
# Author: Martin Pitt <martin.pitt@ubuntu.com>
# License: GPL v2 or higher

set -e

# Install desktop metapackage
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y --force-yes ubuntu-desktop

echo "Setting custom background..."
cp `ls /usr/share/backgrounds/*.jpg | head -n1` $HOME/mybackground.jpg
gconftool -s /desktop/gnome/background/picture_filename --type string $HOME/mybackground.jpg

echo "Setting Radiance theme..."
gconftool -s /desktop/gnome/interface/gtk_theme --type string Radiance

echo "Setting custom keyboard layouts..."
gconftool -s /desktop/gnome/peripherals/keyboard/kbd/layouts --type list --list-type string "[us,de	nodeadkeys,gb,gb	dvorak]"
gconftool -g /desktop/gnome/peripherals/keyboard/kbd/layouts

echo 'Success. Now upgrade to 12.04 LTS and run test_lts_upgrade_user.py'

# Execute User setup script
USERSETUP="/upgrade-tester/data/prepare_lts_user"
TARGETUSER="ubuntu"

if [ -f "$USERSETUP" ]; then
    chmod +x $USERSETUP
    sudo -i -u $TARGETUSER sh $USERSETUP
fi
